services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: derrepente-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: derrepente-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: derrepente-network
