spring:
  datasource:
    url: jdbc:postgresql://${SUPABASE_HOST:db}:${SUPABASE_PORT:5432}/${SUPABASE_DB:postgres}?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: ${SUPABASE_USER:postgres}
    password: ${SUPABASE_PASSWORD:postgrespassword}
    hikari:
      initialization-fail-timeout: 0
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
